### ISSUE TITLE
Request upgrade to support Laravel 6.0

### ISSUE THREAD

**Issue by quangvision** [monicahq/laravel-cloudflare#129]
Hello
Please upgrade this package to support latest version of Laravel 6.0.
Thanks :)

**Comment by insign** [comment]
For Jesus, update this...

**Comment by insign** [comment]
An temporary alternative is follow [this intructions](https://getcomposer.org/doc/05-repositories.md#loading-a-package-from-a-vcs-repository)

**Comment by jeverington** [comment]
@asbiin Thank you!
