### ISSUE TITLE
Runs in testing and local environments

### ISSUE THREAD

**Issue by joelclermont** [monicahq/laravel-cloudflare#250]
I just upgraded from 1.x to 3.x as part of a Laravel 8 -> 9 upgrade, and I was surprised my test suite jumped from 90 seconds to over 6 minutes. After profiling with XDebug, I traced it back to this package. The middleware was running on every feature test and fetching the IPs from Cloudflare, then storing to the cache. But since the cache is `array` for testing, every individual test started with an empty cache causing a lot of calls to Cloudflare.

I'd recommend adding something to the README about this. It was unexpected for me, and I'm probably not the only person who will run into this. Thanks!

**Comment by asbiin** [comment]
Thank you @joelclermont I will fix that by adding a `LARAVEL_CLOUDFLARE_ENABLED` environment variable to deactivate the middleware. You can now add `LARAVEL_CLOUDFLARE_ENABLED=false` in you `.env` or `phpunit.xml` file to avoid this behavior!
