### ISSUE TITLE
I can´t get the visitor real ip ussing this package

### ISSUE THREAD

**Issue by juliangarcess** [monicahq/laravel-cloudflare#259]
I can´t get the visitor real ip ussing this package, please can you asist me?, thanks!

**Comment by asbiin** [comment]
The package itself doesn't aim at helping you get the real ip address.

But if you're behind Cloudflare, you can get the ip adress with
```php
Request::header('Cf-Connecting-Ip')
```
... or you can use some packages like [vectorface/whip](https://packagist.org/packages/vectorface/whip) or [akrabat/ip-address-middleware](https://packagist.org/packages/akrabat/ip-address-middleware)
