### ISSUE TITLE
TrustProxies no longer valid after update to v3.7

### ISSUE THREAD

**Issue by Human018** [monicahq/laravel-cloudflare#285]
## Description
After updating to laravel-cloudflare v3.7 the laravel helper `request()->isFromTrustedProxy()` returns false, meaning any https URL requests get redirected to http, but because I'm enforcing https the project ends up in a 301 redirect loop.

## Expected Behavior
I'm expecting the assigned full qualified URL of my resource (in this case a Page on the project website) to match the requested URL or `request()->url()`.

## Actual Behavior
Unfortunately the `request()->url()` returns a scheme of 'http' because the `request()->isFromTrustedProxy()` returns false.

## Context
In my web.php route file I have the following code:
`
if (
            $resource->uri !== '/' &&
            $resource->url !== request()->url() &&
            $resource->url !== request()->url() . '/'
        ) return redirect($resource->url, 301);
`

This is designed for the requested resource to redirect to the assigned qualified URL - if the http request doesn't match. This includes redirecting the user if they have used a non-secure scheme to request the resource.

## Possible Reason
It seems to be related to how it determines if the current requesting IP is in the Trusted Proxy array as received from Cloudflare. Because the environment 'REMOTE_ADDR' is now being set from 'Cf-Connecting-Ip' it is using the users IP address to determine if it is in the trusted Cloudflare array (which of course it couldn't be).

## Your Environment
Laravel v9.21

**Comment by kohenkatz** [comment]
You can turn off the new behavior by setting `LARAVEL_CLOUDFLARE_REPLACE_IP=false` in your `.env` file.

I am disappointed that this breaking change was made to the package in a minor version bump, and I hope that this will be corrected. My team spent many hours debugging why our signed URLs were failing to validate, and it was because we were generating them with `https://` but this change was causing them to be validated with `http://` - which failed, of course.

**Comment by asbiin** [comment]
@Human018  @kohenkatz I'm sorry, I didn't expected to introduce a disruption, obviously. I will change the default of `LARAVEL_CLOUDFLARE_REPLACE_IP` to `false`, and find a better approach...

**Comment by asbiin** [comment]
fixed by #288

**Comment by kohenkatz** [comment]
@asbiin Thank you for the fix. I understand accidental breaking changes, I've done the same thing myself in the past.
